# Generated by Django 6.0.5 on 2026-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookinfo_options_bookinfo_commentcount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': 'People'},
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='PeopleInfo',
        ),
    ]
