# Generated by Django 6.0.5 on 2026-05-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookinfo_options_alter_peopleinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleinfo',
        ),
    ]
